Check email
IT-Academy-Ruby/lessoner_project_backend pull request #39
Opened 2022-10-03 11:23 UTC by ritamma

2022-10-03 11:59 UTC, fooooxmr requested changes

2022-10-03 11:59 UTC, fooooxmr commented on config/routes.rb
> +    post '/check_email', to: 'users#check_email'
This is should be get endpoint.

2022-10-03 11:59 UTC, fooooxmr commented on app/controllers/users_controller.rb
> +    @user = User.find_by('email = ?', params[:email])
It's better to use `User.find_by(email: params[:email])` here.

2022-10-03 11:59 UTC, fooooxmr commented on app/controllers/users_controller.rb
> +      format.json { render json: { email_exists: @user.present? } }
Use JBuilder instead of such format.

2022-10-03 12:49 UTC, Terapool approved these changes

2022-10-03 13:20 UTC, Dmitryshl approved these changes

2022-10-03 18:47 UTC, fooooxmr approved these changes

2022-10-05 08:33 UTC, evrusha approved these changes

2022-10-13 18:57 UTC, merged