Les 54
IT-Academy-Ruby/lessoner_project_backend pull request #41
Opened 2022-10-03 22:26 UTC by Dmitryshl

2022-10-03 22:29 UTC, fooooxmr requested changes

2022-10-03 22:29 UTC, fooooxmr commented on spec/requests/lessons_spec.rb
> +  path '(/{locale)}/lessons/new' do
There should not be new endpoint. You can remove action.

2022-10-03 22:29 UTC, fooooxmr commented on spec/requests/lessons_spec.rb
> +  # path '(/{locale)}/lessons/{id}/edit' do
Remove this comment, please.

2022-10-03 22:30 UTC, fooooxmr commented on spec/requests/lessons_spec.rb
> +  path '(/{locale)}/lessons/new' do
Also delete routes for new and edit.

2022-10-04 07:52 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
> +  rescue StandardError => e
This is not correct. We should return 404 error only in case of missing record. In other cases we need to return 400 error code.

2022-10-04 07:53 UTC, fooooxmr commented on spec/requests/lessons_spec.rb
> +        example 'application/json', :example_key, {
We also should be able to send a link to the video.

2022-10-04 07:53 UTC, fooooxmr commented on spec/requests/lessons_spec.rb
> +    patch('update lesson') do
We can remove patch also.

2022-10-04 07:53 UTC, fooooxmr approved these changes

2022-10-04 08:10 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
> +  rescue StandardError => e
We can remove this rescue block at all, and rewrite our error pages to the JSON.

2022-10-04 08:23 UTC, fooooxmr commented on spec/requests/lessons_spec.rb
> +    patch('update lesson') do
And please, remove unused routes, actions and views related to the lessons also.

2022-10-04 08:29 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
> +  rescue StandardError => e
It will be nice to investigate question about errors handling in a separate ticket.

2022-10-06 17:19 UTC, olegbrest1 approved these changes

2022-10-08 14:55 UTC, Terapool requested changes
This commit to be recreated. It contains redundant files

2022-10-08 15:09 UTC, ritamma approved these changes

2022-10-11 13:21 UTC, closed without merging