Correction lesson controller
IT-Academy-Ruby/lessoner_project_backend pull request #47
Opened 2022-10-12 19:30 UTC by Dmitryshl

2022-10-13 16:40 UTC, Terapool requested changes
Too many bugs in Lessons requests and corresponding schema

2022-10-13 16:40 UTC, Terapool commented on spec/swagger_helper.rb
>          }
required: %w[id]

2022-10-13 16:40 UTC, Terapool commented on spec/swagger_helper.rb
>            required: %w[title description status video_link author_id]
category_id is required here or not?

2022-10-13 16:40 UTC, Terapool commented on app/views/lessons/show.jbuilder
> +  json.author_id @lesson.author_id
You need to remove 'post' from here. Now you return something like this:

{
  "post": {
    "id": 6,
    "title": "string",
    "description": "string",
    "video_link": "string",
    "author_id": 1,
    "category_id": 1
  }
}

See app/views/categories/show.jbuilder as example

2022-10-13 16:40 UTC, Terapool commented on spec/requests/lessons_spec.rb
>            vvideo_link: 'link',
typo: 'vvideo_link'

2022-10-13 16:40 UTC, Terapool commented on spec/requests/lessons_spec.rb
>            status: 'status',
Actually status is not returned after creation...

2022-10-13 16:40 UTC, Terapool commented on spec/requests/lessons_spec.rb
> +          id: 1,
You can not update id in lesson!!!

2022-10-17 08:29 UTC, Terapool commented on app/views/lessons/show.jbuilder
> +json.id @lesson.id
Why not use json.extract! here?

2022-10-17 19:48 UTC, evrusha commented on app/controllers/lessons_controller.rb
> +      render 'lessons/show'
Just `render :show` ?

2022-10-17 19:48 UTC, evrusha commented on app/views/lessons/show.jbuilder
> +json.status @lesson.status
Better this? `json.extract! @lesson, :id, :title, :description, :video_link, :author_id, :category_id, :status`

2022-10-18 09:27 UTC, evrusha commented on app/controllers/lessons_controller.rb
> +    @lesson = Lesson.all.find_by(id: params[:id])
Why we need `all`?

2022-10-19 08:26 UTC, fooooxmr requested changes

2022-10-19 08:26 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
>        render :new, status: :unprocessable_entity
We do not need to render show here. We need to return an errors with validations or anything else.

2022-10-19 08:26 UTC, fooooxmr commented on app/views/lessons/error.jbuilder
> +json.deleted false
Errors should be more meaningful and should be reused for all errors. Add error message here.

2022-10-24 11:08 UTC, Terapool approved these changes

2022-10-24 12:45 UTC, olegbrest1 approved these changes

2022-10-24 14:15 UTC, fooooxmr approved these changes

2022-10-25 06:38 UTC, evrusha approved these changes

2022-11-10 09:32 UTC, merged