Les72
IT-Academy-Ruby/lessoner_project_backend pull request #54
Opened 2022-10-26 19:26 UTC by Dmitryshl

2022-10-26 19:33 UTC, fooooxmr requested changes

2022-10-26 19:33 UTC, fooooxmr commented on config/routes.rb
> -  post '/login', to: 'sign_up#login', defaults: { format: :json }
Why login endpoint is removed?

2022-10-26 19:33 UTC, fooooxmr commented on swagger/v1/swagger.yaml
> +  "/{locale}/check_email?email={email}":
You need to remove locale from the swagger also.

2022-10-26 19:33 UTC, fooooxmr commented on swagger/v1/swagger.yaml
> +                - email_exists
Why we are renamed username_exists to email_exists?

2022-11-02 08:40 UTC, evrusha reviewed
I'll re-review after the conversations be resolved.

2022-11-08 20:00 UTC, closed without merging

2022-11-08 20:00 UTC, Terapool commented
See https://github.com/IT-Academy-Ruby/lessoner_project_backend/pull/59