Add pagination and filtering for lessons page
IT-Academy-Ruby/lessoner_project_backend pull request #70
Opened 2022-11-29 18:57 UTC by PandaGrom

2022-11-30 10:32 UTC, fooooxmr requested changes

2022-11-30 10:32 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
> +    @pagy, @lessons = pagy(Lesson.filter(lesson_params.slice(:status, :category_id)), items: 3)
How we will receive page, per_page params?
Also we need to add possibility to sort there.

2022-11-30 10:49 UTC, PandaGrom commented on app/controllers/lessons_controller.rb
> +    @pagy, @lessons = pagy(Lesson.filter(lesson_params.slice(:status, :category_id)), items: 3)
Yes

2022-11-30 10:51 UTC, PandaGrom commented on app/controllers/lessons_controller.rb
> +    @pagy, @lessons = pagy(Lesson.filter(lesson_params.slice(:status, :category_id)), items: 3)
Yes, 
e.g. http://127.0.0.1:3000/lessons?page=2&category_id=2&status=active

2022-12-01 12:32 UTC, hannrywislou approved these changes

2022-12-06 05:31 UTC, evrusha approved these changes

2022-12-13 11:22 UTC, merged