Add rating for lessons
IT-Academy-Ruby/lessoner_project_backend pull request #83
Opened 2022-12-15 10:15 UTC by PandaGrom

2022-12-15 10:32 UTC, fooooxmr requested changes

2022-12-15 10:32 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
> +class LessonsController < AuthorizationController
Lessons endpoint should be available for non registred users.

2022-12-15 10:32 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
> +    CalculateLessonsRating.new(lesson: @lesson, current_user:, rating: lesson_rating_params[:rating]).call
Why you are passing current_user: nil?

2022-12-15 10:32 UTC, fooooxmr commented on app/models/lesson.rb
> +  validates :rating, numericality: { less_than_or_equal_to: 5 }
Rating can not be less then 0.

2022-12-15 10:32 UTC, fooooxmr commented on app/services/calculate_lessons_rating.rb
> +class CalculateLessonsRating
It's better to name CalculateLessonsRatingService to make understandable, that this is a service.

2022-12-15 10:32 UTC, fooooxmr commented on app/services/calculate_lessons_rating.rb
> +    @lesson.lesson_ratings.average(:rating)
What is happening in this method?

2022-12-15 10:32 UTC, fooooxmr commented on spec/models/lesson_rating_spec.rb
> +require 'rails_helper'
Do not forget to update swagger.

2022-12-15 10:32 UTC, fooooxmr commented on app/controllers/lessons_controller.rb
> +class LessonsController < AuthorizationController
Only endpoint with setting rating should be secure from guests.

2022-12-18 10:34 UTC, evrusha reviewed
I will re-review after conversations be resolved.

2022-12-22 09:42 UTC, Terapool approved these changes

2022-12-22 09:58 UTC, fooooxmr approved these changes

2022-12-22 10:26 UTC, evrusha approved these changes

2022-12-26 16:26 UTC, merged